# Generated by Django 4.1.7 on 2023-03-07 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='brand',
            options={'verbose_name': '4. Brand'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '1. Category'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': '5. Product'},
        ),
        migrations.AlterModelOptions(
            name='subcategory',
            options={'verbose_name': '2. SubCategory'},
        ),
        migrations.AlterModelOptions(
            name='type',
            options={'verbose_name': '3. Type'},
        ),
    ]
